<?php

namespace AppBundle\Repository;

/**
 * CompetitorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitorsRepository extends \Doctrine\ORM\EntityRepository
{
}
